language: java
notifications:
  slack:
    secure: PjMUoad1n8yEPeGD89lwxxw/UQL2cMv2Af3hItRmmEaQdkNgnfIEELPu+7ZMXiohbySAoZm+SNVWHCf5AoI+3z5Nu/8ExCcZtkcuCZVrMsn2UqNkwJbOq+6XUelSyAUmVIs58SrQVya8US0EzMxgytk7gnN4zZkWqsn9JnlGMk0=
deploy:
  provider: releases
  api_key:
    secure: J6HD1ML2EcjDkhdjmJZCjlTMl69qW4k8eVd87yLXJ09puelCMm8HNMBHR3PIboJiu7dzRkrurRaZVORhi9LmcPn/IvwLnSfT69MLGqr4xXFixS7vDF72HDQ69yaLgPKqK3vZj3FHZR/bQTSD5hatYhM51265d6VRxvZwV8sCxKk=
  file: build/libs/xld-lock-plugin-5.1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-lock-plugin
